<#
.SYNOPSIS
    Generates the EXPORTS list for the console build of xgameruntime.thunks.dll.

.DESCRIPTION
    Reads the public symbols out of the GXDK's own xgameruntime.lib and writes a .def naming every
    X* entry point. The linker then re-exports the GDK's own stubs by name - see
    XGameRuntimeThunks.cpp for why that is the whole implementation.

    Generated at build time rather than checked in so the export list always matches the installed
    GDK edition. __stdcall is not name-decorated on x64, so the names need no decoration.

.PARAMETER Library
    Path to the console xgameruntime.lib.

.PARAMETER OutputPath
    Where to write the .def.

.PARAMETER DumpBin
    Path to dumpbin.exe. Defaults to the one beside the MSVC toolset in PATH.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string] $Library,
    [Parameter(Mandatory)][string] $OutputPath,
    [string] $DumpBin
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path $Library)) {
    throw "The console xgameruntime.lib was not found at '$Library'. Install the Microsoft GDK's Xbox extensions."
}

if (-not $DumpBin) {
    # Written for Windows PowerShell 5.1 as well as pwsh: no null-conditional operator.
    $command = Get-Command 'dumpbin.exe' -ErrorAction SilentlyContinue
    if ($command) { $DumpBin = $command.Source }
}
if (-not $DumpBin -or -not (Test-Path $DumpBin)) {
    # The build passes this in; the fallback is for running the script by hand.
    $DumpBin = Get-ChildItem 'C:\Program Files\Microsoft Visual Studio' -Recurse -Filter 'dumpbin.exe' -ErrorAction SilentlyContinue |
        Where-Object { $_.FullName -match 'Hostx64\\x64' } | Sort-Object FullName -Descending | Select-Object -First 1 -ExpandProperty FullName
}
if (-not $DumpBin) { throw 'dumpbin.exe was not found. Run this from a Visual Studio developer prompt, or pass -DumpBin.' }

# /linkermember:1 lists the archive's public symbols as "<offset> <name>" pairs.
$symbols = & $DumpBin /linkermember:1 $Library |
    ForEach-Object { if ($_ -match '^\s{4,}[0-9A-Fa-f]+\s+(\S+)\s*$') { $Matches[1] } } |
    Where-Object { $_ -clike 'X*' } |
    Sort-Object -Unique

if ($symbols.Count -lt 100) {
    throw "Only $($symbols.Count) X* symbols were found in '$Library'; expected several hundred. The dumpbin output format may have changed."
}

$header = @(
    '; Generated by Generate-Def.ps1 - do not edit, and do not check in.'
    ";"
    "; Source: $Library"
    "; Symbols: $($symbols.Count)"
    ';'
    '; Every name below is resolved by the linker directly out of xgameruntime.lib, so the exported'
    '; function IS the GDK''s own stub. There is deliberately no wrapper code - see'
    '; XGameRuntimeThunks.cpp.'
    ';'
    '; No LIBRARY directive: the output name comes from /OUT:, and a LIBRARY line here would'
    '; override it.'
    ''
    'EXPORTS'
)

$body = $symbols | ForEach-Object { "    $_" }

$new = ($header + $body) -join "`r`n"

# Only rewrite when the content actually changes, so MSBuild does not relink every build.
$existing = if (Test-Path $OutputPath) { Get-Content $OutputPath -Raw } else { $null }
if ($existing -ne ($new + "`r`n")) {
    New-Item -ItemType Directory -Force (Split-Path -Parent $OutputPath) | Out-Null
    Set-Content -Path $OutputPath -Value $new -Encoding ASCII
    Write-Host "Wrote $($symbols.Count) exports to $OutputPath"
}
else {
    Write-Host "$OutputPath is up to date ($($symbols.Count) exports)"
}
